Updated sample to use MSAL
msintuneappsdk/Taskr-Sample-Intune-Xamarin-Android-Apps pull request #16
Opened 2021-03-11 19:01 UTC by marcusca10

Updated sample to use MSAL instead of ADAL.
Code, comments and README

2021-03-11 19:09 UTC, cofitz1 commented on TaskrAndroid/MainActivity.cs
> +                //handler.SendEmptyMessage((int)PromptBehavior.Always);
should we remove this line?

2021-03-16 17:52 UTC, marcusca10 commented on TaskrAndroid/MainActivity.cs
> +                //handler.SendEmptyMessage((int)PromptBehavior.Always);
Sure, let me remove the comment from the branch.

2021-03-16 18:17 UTC, meghandaly requested changes

2021-03-16 18:17 UTC, meghandaly commented on TaskrAndroid/Properties/AndroidManifest.xml
>    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
These permissions are no longer needed, IIRC.

2021-03-16 18:17 UTC, meghandaly commented on TaskrForms/TaskrForms.Android/Properties/AndroidManifest.xml
> +    <!-- Required for Broker usage with MSAL -->
Also not needed here.

2021-03-16 18:17 UTC, meghandaly commented on TaskrForms/TaskrForms.Android/TaskrForms.Android.csproj
> +  <ProjectExtensions>
What is the purpose of this change?

2021-03-17 08:19 UTC, marcusca10 commented on TaskrForms/TaskrForms.Android/TaskrForms.Android.csproj
> +  <ProjectExtensions>
This was added by Visual Studio after changing the Linker option, as it's incompatible with Hot Reload. I'll remove it from the file as it doesn't affect the project (just the yellow bar with a message in VS), but it may get added again in the future.

2021-03-17 08:28 UTC, marcusca10 commented on TaskrAndroid/Properties/AndroidManifest.xml
>    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
Correct, I'll remove them and test before committing... Just in case.

2021-03-17 08:28 UTC, marcusca10 commented on TaskrForms/TaskrForms.Android/Properties/AndroidManifest.xml
> +    <!-- Required for Broker usage with MSAL -->
Same as previous

2021-04-21 13:15 UTC, marcusca10 commented on TaskrAndroid/Properties/AndroidManifest.xml
>    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
All set, last commit has it removed.

2021-04-21 13:40 UTC, meghandaly approved these changes

2021-04-21 13:41 UTC, meghandaly commented
@marcusca10 Thank you for making the changes and for submitting this PR in general! Merging now! 👍

2021-04-21 13:41 UTC, merged

2021-04-21 13:44 UTC, bgavrilMS commented
Great work!